from pathlib import Path

SRC = Path('marwa-interactive.html')
OUT = Path('marwa-motion.html')

s = SRC.read_text(encoding='utf-8')

# Always derive the motion version from the preserved interactive version.
if 'MARWA-INTERACTIVE-V2' not in s:
    raise SystemExit('Expected preserved interactive source was not found')

# Small structural hooks only in the new motion version.
s = s.replace('<div class="fx" id="fx"></div>', '<div class="fx" id="fx"></div><div class="motion-fx" id="motionFx"></div><div class="motion-wash" id="motionWash"></div>', 1)
s = s.replace('<div class="icon motion-cap">🎓</div>', '<div class="icon motion-cap">🎓</div>', 1)
if '<div class="icon">🎓</div>' in s:
    s = s.replace('<div class="icon">🎓</div>', '<div class="icon motion-cap">🎓</div>', 1)
s = s.replace('<button class="btn" onclick="go(2)">ابدئي الرحلة ✨</button>', '<button class="btn" id="startJourney" onclick="go(2)">ابدئي الرحلة ✨</button>', 1)
s = s.replace('<div class="cover">🎓</div>', '<div class="cover" id="songCover">🎓</div>', 1)

css = r'''/* MARWA-MOTION-V3 */
html{scroll-behavior:smooth}.app{isolation:isolate}.app:before,.app:after{content:'';position:absolute;z-index:0;width:42vw;height:42vw;max-width:420px;max-height:420px;border-radius:50%;filter:blur(18px);opacity:.18;pointer-events:none;animation:ambientBlob 12s ease-in-out infinite}.app:before{left:-15%;top:10%;background:#e5a4b5}.app:after{right:-15%;bottom:5%;background:#e6c774;animation-delay:-5s}@keyframes ambientBlob{0%,100%{transform:translate3d(0,0,0) scale(1)}35%{transform:translate3d(32px,-20px,0) scale(1.08)}70%{transform:translate3d(-16px,28px,0) scale(.94)}}
.top,.scene{z-index:2}.motion-fx{position:absolute;inset:0;z-index:3;pointer-events:none;overflow:hidden}.motion-spark{position:absolute;bottom:-20px;color:#fff7dd;opacity:0;animation:sparkFloat 5.4s linear forwards;text-shadow:0 0 12px rgba(255,255,255,.35)}@keyframes sparkFloat{0%{transform:translateY(0) scale(.7) rotate(0);opacity:0}15%{opacity:.45}75%{opacity:.28}100%{transform:translateY(-105vh) scale(1.15) rotate(80deg);opacity:0}}.motion-wash{position:absolute;inset:0;z-index:55;pointer-events:none;opacity:0;transition:opacity .2s ease;background:#130b0e}.motion-wash.on{opacity:.72}.motion-wash.gold{background:radial-gradient(circle,#b89042,#1a0d12)}
.btn,.ans,.gift-pick{transition:transform .18s cubic-bezier(.2,.8,.2,1),box-shadow .22s ease,filter .22s ease,background .22s ease}.btn:active,.ans:active,.gift-pick:active{transform:scale(.96)!important}.btn:not(:disabled):hover,.ans:not(:disabled):hover{transform:translateY(-2px)}
.scene.motion-leave .panel{animation:sceneLeave .22s ease both}.scene.motion-enter .panel{animation:sceneEnter .48s cubic-bezier(.18,.8,.22,1) both}@keyframes sceneEnter{from{opacity:0;transform:translateY(22px) scale(.975);filter:blur(5px)}to{opacity:1;transform:none;filter:none}}@keyframes sceneLeave{to{opacity:0;transform:translateX(22px) scale(.985);filter:blur(3px)}}
.motion-item{opacity:0;animation:softRise .5s var(--motion-delay,0s) cubic-bezier(.18,.8,.22,1) forwards}@keyframes softRise{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:none}}
.motion-cap{animation:capDrop .8s .08s cubic-bezier(.2,.85,.2,1.25) both!important}@keyframes capDrop{0%{opacity:0;transform:translateY(-70px) rotate(-9deg) scale(.75)}65%{opacity:1;transform:translateY(8px) rotate(4deg) scale(1.06)}82%{transform:translateY(-4px) rotate(-2deg) scale(.98)}100%{transform:none}}
#startJourney{animation:startBreathe 2.2s 2.2s ease-in-out infinite}@keyframes startBreathe{0%,100%{transform:scale(1);box-shadow:0 14px 28px #8c4b5c38}50%{transform:scale(1.025);box-shadow:0 18px 34px #8c4b5c55}}
.scene[data-s="2"].motion-enter .chip{animation:eyePeek .75s .2s both}@keyframes eyePeek{0%{opacity:0;transform:translateX(12px) rotate(4deg)}45%{opacity:1;transform:translateX(-5px) rotate(-3deg)}100%{transform:none}}
.ans.ok{animation:correctPop .42s ease both}.ans.bad{animation:wrongShake .42s ease both}@keyframes correctPop{45%{transform:scale(1.035)}100%{transform:none}}@keyframes wrongShake{0%,100%{transform:translateX(0)}20%{transform:translateX(7px)}40%{transform:translateX(-7px)}60%{transform:translateX(5px)}80%{transform:translateX(-3px)}}
.bar i{transition:width .65s cubic-bezier(.2,.8,.2,1)!important}.infinity-flash{position:absolute;z-index:70;inset:0;display:grid;place-items:center;pointer-events:none;font-size:min(42vw,180px);font-weight:900;color:#b66c7e;text-shadow:0 12px 60px rgba(140,75,92,.3);animation:infinityPop .7s ease both}@keyframes infinityPop{0%{opacity:0;transform:scale(.35) rotate(-12deg)}40%{opacity:.94;transform:scale(1.1) rotate(5deg)}100%{opacity:0;transform:scale(1.35) rotate(0)}}
.scene[data-s="3"] .quote.motion-highlight{animation:quoteGlow .75s ease both}@keyframes quoteGlow{0%{opacity:0;transform:scale(.96);box-shadow:0 0 0 rgba(201,168,93,0)}55%{opacity:1;transform:scale(1.025);box-shadow:0 12px 32px rgba(201,168,93,.15)}100%{transform:none}}
.analysis-percent.analysis-stuck{animation:stuckNumber .24s linear 4}@keyframes stuckNumber{0%,100%{transform:translateX(0)}33%{transform:translateX(3px)}66%{transform:translateX(-3px)}}.analysis-sub.dots:after{content:'...';display:inline-block;width:18px;overflow:hidden;vertical-align:bottom;animation:dots 1s steps(4,end) infinite}@keyframes dots{0%{width:0}100%{width:18px}}
.scene[data-s="4"].motion-enter .chip{animation:alertFlash .7s .12s ease both}.scene[data-s="4"].motion-enter h2{animation:dangerNudge .5s .35s ease both}@keyframes alertFlash{0%{opacity:0;transform:scale(.8);box-shadow:0 0 0 0 rgba(239,92,92,.45)}45%{opacity:1;transform:scale(1.07);box-shadow:0 0 0 14px rgba(239,92,92,0)}100%{transform:none}}@keyframes dangerNudge{0%,100%{transform:none}35%{transform:translateX(4px)}65%{transform:translateX(-4px)}}#d4.hint-glow{animation:hintGlow 1.4s ease-in-out infinite}@keyframes hintGlow{0%,100%{box-shadow:inset 0 0 0 1px #ffffff14,0 0 0 rgba(239,216,151,0)}50%{box-shadow:inset 0 0 0 1px #efd89788,0 0 28px #efd89732}}
.gift-pick{animation:boxIdle 2.7s ease-in-out infinite}.gift-pick:nth-child(2){animation-delay:-.8s}.gift-pick:nth-child(3){animation-delay:-1.6s}@keyframes boxIdle{0%,100%{transform:translateY(0) rotate(0)}50%{transform:translateY(-5px) rotate(1deg)}}.gift-pick.selected{animation:boxOpen .55s cubic-bezier(.2,.85,.2,1.2) both!important}.gift-pick.selected .gift-emoji{animation:ribbonOpen .55s ease both}@keyframes boxOpen{40%{transform:translateY(-12px) scale(1.09) rotate(-2deg)}75%{transform:translateY(2px) scale(.98) rotate(1deg)}100%{transform:scale(1.025)}}@keyframes ribbonOpen{35%{transform:scale(1.25) rotate(-12deg)}100%{transform:none}}.gift-mini-fx{position:absolute;z-index:80;pointer-events:none;font-size:25px;animation:giftMini 1.2s ease-out forwards}@keyframes giftMini{to{transform:translate(var(--dx),-95px) rotate(var(--rot));opacity:0}}
.scene[data-s="5"].motion-enter .file{animation:fileSlide .65s .08s cubic-bezier(.18,.8,.22,1) both}@keyframes fileSlide{from{opacity:0;transform:translateY(22px) rotateX(8deg) scale(.97)}to{opacity:1;transform:none}}.status-value.loading{color:#e8c96f}.status-value.ready{color:#90dfb5;animation:statusPop .4s ease both}@keyframes statusPop{50%{transform:scale(1.08)}}
.stat-row.show b.counting{font-variant-numeric:tabular-nums}.grad-result.show{position:relative;overflow:visible}.grad-result.show:after{content:'APPROVED ✓';position:absolute;left:12px;top:-17px;border:2px solid #8fd4ad;color:#8fd4ad;padding:4px 9px;border-radius:7px;font:900 12px Tahoma,Arial,sans-serif;transform:rotate(-8deg);animation:stampIn .52s .25s cubic-bezier(.15,.9,.3,1.25) both}@keyframes stampIn{0%{opacity:0;transform:rotate(-8deg) scale(1.8)}65%{opacity:1;transform:rotate(-8deg) scale(.92)}100%{transform:rotate(-8deg) scale(1)}}
.sound-wave{display:flex;justify-content:center;align-items:center;gap:4px;height:38px;margin:10px 0}.sound-wave i{display:block;width:5px;height:8px;border-radius:99px;background:#c9a85d;animation:waveBar .65s ease-in-out infinite}.sound-wave i:nth-child(2),.sound-wave i:nth-child(6){animation-delay:-.15s}.sound-wave i:nth-child(3),.sound-wave i:nth-child(5){animation-delay:-.3s}.sound-wave i:nth-child(4){animation-delay:-.45s}@keyframes waveBar{50%{height:31px;background:#9b5668}}.focus-heart{position:absolute;z-index:90;left:50%;top:50%;pointer-events:none;font-size:88px;animation:focusHeart 1.15s ease forwards}@keyframes focusHeart{0%{opacity:0;transform:translate(-50%,-50%) scale(.3)}38%{opacity:1;transform:translate(-50%,-50%) scale(1.12)}100%{opacity:0;transform:translate(-50%,-105%) scale(.75)}}
.scene[data-s="6"] .quote{position:relative;border-right:0;overflow:hidden}.scene[data-s="6"] .quote:before{content:'';position:absolute;right:0;top:0;width:4px;height:0;background:var(--g);border-radius:99px}.scene[data-s="6"].motion-enter .quote:before{animation:borderGrow .9s .5s ease forwards}@keyframes borderGrow{to{height:100%}}.scene[data-s="6"].motion-enter h2[style]{animation:graduateGlow .7s .65s ease both}@keyframes graduateGlow{from{opacity:0;transform:scale(.95);text-shadow:0 0 0 rgba(143,76,93,0)}to{opacity:1;transform:none;text-shadow:0 8px 28px rgba(143,76,93,.12)}}
.countdown.count-pop{animation:countPop .62s cubic-bezier(.18,.8,.22,1.25) both}@keyframes countPop{0%{opacity:0;transform:scale(1.6)}55%{opacity:1;transform:scale(.9)}100%{transform:scale(1)}}.countdown.count-pop:after{content:'';position:absolute;left:50%;top:50%;width:120px;height:120px;border:2px solid rgba(255,240,201,.28);border-radius:50%;transform:translate(-50%,-50%);animation:ringOut .65s ease-out both}@keyframes ringOut{to{width:210px;height:210px;opacity:0}}.gift.gift-opening{animation:giftOpenReal .45s ease both!important}@keyframes giftOpenReal{25%{transform:scale(.9) rotate(-7deg)}60%{transform:scale(1.22) rotate(8deg)}100%{transform:scale(1.05) rotate(0)}}#lastq:not(.hide){animation:fakeOut .48s cubic-bezier(.18,.8,.22,1.2) both}@keyframes fakeOut{0%{opacity:0;transform:scale(.78) rotate(-2deg)}70%{opacity:1;transform:scale(1.035) rotate(1deg)}100%{transform:none}}
.audio-file{position:relative;overflow:hidden}.audio-file:after{content:'';position:absolute;left:-35%;top:0;width:28%;height:100%;background:linear-gradient(90deg,transparent,rgba(235,211,141,.13),transparent);transform:skewX(-12deg)}#audioGateOverlay.show .audio-file:after{animation:fileScan 1.35s ease-in-out 1}@keyframes fileScan{to{left:115%}}.audio-file-name{overflow:hidden;white-space:nowrap;width:0}#audioGateOverlay.show .audio-file-name{animation:fileTyping 1.05s .15s steps(20,end) forwards}@keyframes fileTyping{to{width:100%}}#audioGateOverlay.show .audio-meta div{opacity:0;animation:metaReveal .42s ease forwards}#audioGateOverlay.show .audio-meta div:nth-child(1){animation-delay:.45s}#audioGateOverlay.show .audio-meta div:nth-child(2){animation-delay:.62s}#audioGateOverlay.show .audio-meta div:nth-child(3){animation-delay:.79s}#audioGateOverlay.show .audio-meta div:nth-child(4){animation-delay:.96s}@keyframes metaReveal{from{opacity:0;transform:translateY(7px)}to{opacity:1;transform:none}}.gate-status:not(.gate-ready){animation:lockShake .55s .8s ease both}@keyframes lockShake{0%,100%{transform:none}30%{transform:translateX(4px)}60%{transform:translateX(-4px)}}.gate-status.gate-ready{animation:unlockPop .45s ease both}@keyframes unlockPop{50%{transform:scale(1.07)}}#audioGateOverlay.portal-close .moment-card{animation:portalZoom .48s ease-in both}@keyframes portalZoom{to{opacity:0;transform:scale(1.35);filter:blur(8px)}}
.cover{position:relative;animation:coverFloat 4.5s ease-in-out infinite}@keyframes coverFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-8px)}}.cover:before{content:'';position:absolute;inset:-9px;border:1px solid rgba(238,212,141,.26);border-radius:35px;box-shadow:0 0 34px rgba(238,212,141,.11);animation:ringBreath 3.2s ease-in-out infinite}@keyframes ringBreath{50%{inset:-15px;opacity:.38}}.cover.playing{animation:coverPlaying 2.2s ease-in-out infinite}@keyframes coverPlaying{0%,100%{transform:translateY(-4px) scale(1)}50%{transform:translateY(-7px) scale(1.025)}}.song-particle{position:absolute;z-index:70;pointer-events:none;color:#fff4d7;animation:songParticle 3.8s linear forwards}@keyframes songParticle{to{transform:translateY(-180px) rotate(55deg);opacity:0}}
#downloadSongBtn:active{transform:scale(.97)}#ending{transform-origin:top center}#ending.letter-opening{animation:letterOpen .7s cubic-bezier(.18,.8,.22,1) both}@keyframes letterOpen{0%{opacity:0;transform:perspective(700px) rotateX(-24deg) scaleY(.72)}100%{opacity:1;transform:none}}#ending.letter-opening>*{opacity:0;animation:finalLine .5s ease forwards}@keyframes finalLine{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}#ending.letter-opening>*:nth-child(1){animation-delay:.25s}#ending.letter-opening>*:nth-child(2){animation-delay:.4s}#ending.letter-opening>*:nth-child(3){animation-delay:.55s}#ending.letter-opening>*:nth-child(4){animation-delay:.7s}#ending.letter-opening>*:nth-child(5){animation-delay:.85s}#ending.letter-opening>*:nth-child(6){animation-delay:1s}#ending.letter-opening>*:nth-child(7){animation-delay:1.15s}#ending h3{font-size:24px;transform-origin:center}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important}}
'''
s = s.replace('</style>', css + '</style>', 1)

js = r'''/* MARWA-MOTION-V3-JS */
const motionApp=document.querySelector('.app'),motionFx=$('motionFx'),motionWash=$('motionWash');
function motionReflow(el,cls){if(!el)return;el.classList.remove(cls);void el.offsetWidth;el.classList.add(cls)}
function addMotionItems(nodes,start=.08,step=.09){nodes.forEach((el,i)=>{el.classList.remove('motion-item');void el.offsetWidth;el.style.setProperty('--motion-delay',(start+i*step)+'s');el.classList.add('motion-item')})}
function motionEnter(n){const sc=document.querySelector('[data-s="'+n+'"]');if(!sc)return;document.querySelectorAll('.scene.motion-enter').forEach(x=>x.classList.remove('motion-enter'));sc.classList.add('motion-enter');setTimeout(()=>sc.classList.remove('motion-enter'),1300);if(n===1){addMotionItems([...sc.querySelectorAll('h1,p,.btn')],.18,.10)}if(n===2){addMotionItems([...sc.querySelectorAll('h2,.lead,.ans')],.1,.07)}if(n===3){addMotionItems([...sc.querySelectorAll('h2,.lead,.ans')],.08,.06)}if(n===5){prepareSecretStatus()}if(n===6){addMotionItems([...sc.querySelectorAll('h2,p,h3,.answers,.btn')],.08,.10)}if(n===8){addMotionItems([...sc.querySelectorAll('h2,p,.player,#downloadSongBtn,.quote,.btn')],.08,.08)}}
let motionNavLock=false;const baseGo=go;go=function(n){if(motionNavLock)return;const old=document.querySelector('[data-s="'+cur+'"]');if(old)old.classList.add('motion-leave');motionNavLock=true;if(n===7||n===8){motionWash.classList.toggle('gold',n===8);motionWash.classList.add('on')}setTimeout(()=>{if(old)old.classList.remove('motion-leave');baseGo(n);motionEnter(n);motionNavLock=false;setTimeout(()=>motionWash.classList.remove('on','gold'),260)},220)};
function ambientSpark(){if(document.hidden||!motionFx)return;const e=document.createElement('span');e.className='motion-spark';e.textContent=Math.random()>.55?'✦':'·';e.style.left=(5+Math.random()*90)+'%';e.style.fontSize=(10+Math.random()*10)+'px';e.style.animationDuration=(4.5+Math.random()*2.2)+'s';motionFx.appendChild(e);setTimeout(()=>e.remove(),7000)}setInterval(ambientSpark,1150);setTimeout(()=>{for(let i=0;i<4;i++)setTimeout(ambientSpark,i*260)},300);
function flashInfinity(){const e=document.createElement('div');e.className='infinity-flash';e.textContent='∞';motionApp.appendChild(e);setTimeout(()=>e.remove(),800)}const infinityBtn=[...document.querySelectorAll('[data-s="3"] .ans')].find(b=>b.textContent.includes('الرقم غير قابل للحساب'));if(infinityBtn)infinityBtn.addEventListener('click',flashInfinity);
const r3=document.querySelector('#r3 .quote');if(r3){new MutationObserver(()=>{if(!$('r3').classList.contains('hide'))motionReflow(r3,'motion-highlight')}).observe($('r3'),{attributes:true,attributeFilter:['class']})}
const analysisPct=$('analysisPercent'),analysisSub=$('analysisStatus');if(analysisPct){new MutationObserver(()=>{if(analysisPct.textContent.trim()==='99%'){motionReflow(analysisPct,'analysis-stuck');analysisSub.classList.add('dots')}else{analysisSub.classList.remove('dots')}}).observe(analysisPct,{childList:true,characterData:true,subtree:true})}
const baseQ4=q4;q4=function(b,o){baseQ4(b,o);if(!o&&$('d4'))$('d4').classList.add('hint-glow');if(o&&$('d4'))$('d4').classList.remove('hint-glow')};
function miniGiftBurst(btn,n){const icons=n===1?['📜','✨','🎓']:n===2?['💤','😴','✨']:['❤️','👀','✨'];const r=btn.getBoundingClientRect();icons.forEach((t,i)=>{for(let k=0;k<2;k++){const e=document.createElement('span');e.className='gift-mini-fx';e.textContent=t;e.style.left=(r.left+r.width/2-10)+'px';e.style.top=(r.top+r.height/2-10)+'px';e.style.setProperty('--dx',((i-1)*42+(Math.random()*24-12))+'px');e.style.setProperty('--rot',(Math.random()*80-40)+'deg');document.body.appendChild(e);setTimeout(()=>e.remove(),1300)}})}const baseChooseGiftBox=chooseGiftBox;chooseGiftBox=function(btn,n){baseChooseGiftBox(btn,n);miniGiftBurst(btn,n)};
function prepareSecretStatus(){const fields=[...document.querySelectorAll('[data-s="5"] .field')];const f=fields.find(x=>x.textContent.includes('STATUS'));if(!f)return;f.innerHTML='<small>STATUS</small><span class="status-value loading">LOADING...</span>'}function revealSecretStatus(){const v=document.querySelector('[data-s="5"] .status-value');if(v){v.textContent='TOP SECRET';v.classList.remove('loading');v.classList.add('ready')}}const baseFinishStats=finishStats;finishStats=function(){revealSecretStatus();baseFinishStats()};
function animateNum(el,to,dur=900){if(!el)return;const st=performance.now();el.classList.add('counting');function f(now){const p=Math.min(1,(now-st)/dur),e=1-Math.pow(1-p,3);el.textContent='+'+Math.floor(to*e);if(p<1)requestAnimationFrame(f);else{el.textContent='+'+to;el.classList.remove('counting')}}requestAnimationFrame(f)}const baseStartStats=startSecretStats;startSecretStats=function(){const vals=[...document.querySelectorAll('#statsOverlay .stat-row b')];if(vals[1])vals[1].textContent='+0';baseStartStats();setTimeout(()=>animateNum(vals[1],999,950),980);setTimeout(()=>{$('giveUpBar').style.width='17%'},2180);setTimeout(()=>{$('giveUpBar').style.width='0%'},2940)};
function soundWave(){const m=document.querySelector('.memory');if(!m||m.querySelector('.sound-wave'))return;const w=document.createElement('div');w.className='sound-wave';w.innerHTML='<i></i><i></i><i></i><i></i><i></i><i></i><i></i>';m.appendChild(w);setTimeout(()=>w.remove(),2300)}const baseMem=mem;mem=function(b,o){baseMem(b,o);if(o)soundWave()};
function focusHeart(){const h=document.createElement('div');h.className='focus-heart';h.textContent='❤️';motionApp.appendChild(h);setTimeout(()=>h.remove(),1300)}const basePr=pr;pr=function(b,o){basePr(b,o);if(o)focusHeart()};
const cd=$('cd');if(cd){new MutationObserver(()=>motionReflow(cd,'count-pop')).observe(cd,{childList:true,characterData:true,subtree:true})}
let realGiftOpening=false;const baseOpenGift=openGift;openGift=function(){if(realGiftOpening)return;realGiftOpening=true;const g=document.querySelector('#gift .gift');if(g){g.classList.add('gift-opening');const r=g.getBoundingClientRect();for(let i=0;i<8;i++){const e=document.createElement('span');e.className='gift-mini-fx';e.textContent=i%2?'✨':'🤍';e.style.left=(r.left+r.width/2)+'px';e.style.top=(r.top+r.height/2)+'px';e.style.setProperty('--dx',(Math.random()*130-65)+'px');e.style.setProperty('--rot',(Math.random()*120-60)+'deg');document.body.appendChild(e);setTimeout(()=>e.remove(),1300)}}setTimeout(()=>{baseOpenGift();realGiftOpening=false},420)};
const baseOpenAudioGate=openAudioGate;openAudioGate=function(){baseOpenAudioGate();const o=$('audioGateOverlay');o.classList.remove('portal-close')};const baseFinishAudioGate=finishAudioGate;let portalBusy=false;finishAudioGate=function(){if(portalBusy)return;portalBusy=true;$('audioGateOverlay').classList.add('portal-close');setTimeout(()=>{baseFinishAudioGate();$('audioGateOverlay').classList.remove('portal-close');portalBusy=false},460)};
const song=$('song'),cover=$('songCover')||document.querySelector('.cover');let songParticleTimer=null;function songParticle(){if(!cover||!song||song.paused)return;const r=cover.getBoundingClientRect(),e=document.createElement('span');e.className='song-particle';e.textContent=Math.random()>.5?'🤍':'✦';e.style.left=(r.left+Math.random()*r.width)+'px';e.style.top=(r.top+r.height*.75)+'px';e.style.fontSize=(10+Math.random()*10)+'px';document.body.appendChild(e);setTimeout(()=>e.remove(),4000)}if(song){song.addEventListener('play',()=>{cover&&cover.classList.add('playing');clearInterval(songParticleTimer);songParticleTimer=setInterval(songParticle,720)});['pause','ended'].forEach(ev=>song.addEventListener(ev,()=>{cover&&cover.classList.remove('playing');clearInterval(songParticleTimer)}))}
const dl=$('downloadSongBtn');if(dl){new MutationObserver(()=>{if(dl.textContent.includes('جاري'))dl.style.transform='scale(.985)';else dl.style.transform=''}).observe(dl,{childList:true,characterData:true,subtree:true})}
finish=function(){const e=$('ending');e.classList.add('show','letter-opening');hearts(8);setTimeout(()=>e.scrollIntoView({behavior:'smooth',block:'start'}),250)};
setTimeout(()=>motionEnter(cur),120);
'''
s = s.replace('</script>', js + '</script>', 1)

# New version only; source remains byte-for-byte untouched.
OUT.write_text(s, encoding='utf-8')
print(f'Wrote {OUT} from preserved {SRC}')
